version: '{build}'
init:
    - cmd: python -m pip install -U pip
    - cmd: pip install pipenv
    - cmd: pip install poetry==1.0.0a2
    - ps: npm i -g serverless
build: off
test_script:
    - cmd: >-
        npm i

        node test.js
